// Nichmat Kol Haï — Nous-sa'h Sefarad (source : Wikisource hébreu)
// Hébreu vocalisé + phonétique française fidèle + traduction française.
export const NICHMAT_PRAYER = {
  hebrew: `נִשְׁמַת כָּל חַי תְּבָרֵךְ אֶת שִׁמְךָ, יְהוָה אֱלֹהֵינוּ, וְרוּחַ כָּל בָּשָׂר תְּפָאֵר וּתְרוֹמֵם זִכְרְךָ, מַלְכֵּנוּ, תָּמִיד. מִן הָעוֹלָם וְעַד הָעוֹלָם אַתָּה אֵל, וּמִבַּלְעָדֶיךָ אֵין לָנוּ מֶלֶךְ גּוֹאֵל וּמוֹשִׁיעַ, פּוֹדֶה וּמַצִּיל וּמְפַרְנֵס וְעוֹנֶה וּמְרַחֵם בְּכָל עֵת צָרָה וְצוּקָה. אֵין לָנוּ מֶלֶךְ עוֹזֵר וְסוֹמֵךְ אֶלָּא אָתָּה. אֱלֹהֵי הָרִאשׁוֹנִים וְהָאַחֲרוֹנִים, אֱלוֹהַּ כָּל בְּרִיּוֹת, אֲדוֹן כָּל תּוֹלָדוֹת, הַמְהֻלָּל בְּרֹב הַתִּשְׁבָּחוֹת, הַמְנַהֵג עוֹלָמוֹ בְּחֶסֶד וּבְרִיּוֹתָיו בְּרַחֲמִים. וַיהוָה עֵר הִנֵּה לֹא יָנוּם וְלֹא יִישָׁן, הַמְעוֹרֵר יְשֵׁנִים וְהַמֵּקִיץ נִרְדָּמִים, וְהַמֵּשִׂיחַ אִלְּמִים וְהַמַּתִּיר אֲסוּרִים וְהַסּוֹמֵךְ נוֹפְלִים וְהַזּוֹקֵף כְּפוּפִים וְהַמְפַעֲנֵחַ נֶעֱלָמִים. וּלְךָ לְבַדְּךָ אֲנַחְנוּ מוֹדִים.
וְאִלּוּ פִינוּ מָלֵא שִׁירָה כַּיָּם, וּלְשׁוֹנֵנוּ רִנָּה כַּהֲמוֹן גַּלָּיו, וְשִׂפְתוֹתֵינוּ שֶׁבַח כְּמֶרְחֲבֵי רָקִיעַ, וְעֵינֵינוּ מְאִירוֹת כַּשֶּׁמֶשׁ וְכַיָּרֵחַ, וְיָדֵינוּ פְרוּשׂוֹת כְּנִשְׂרֵי שָׁמַיִם, וְרַגְלֵינוּ קַלּוֹת כָּאַיָּלוֹת, אֵין אֲנַחְנוּ מַסְפִּיקִים לְהוֹדוֹת לְךָ, יְהוָה אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ, וּלְבָרֵךְ אֶת שִׁמְךָ מַלְכֵּנוּ עַל אַחַת מֵאָלֶף, אֶלֶף אַלְפֵי אֲלָפִים וְרִבֵּי רְבָבוֹת פְּעָמִים, הַטּוֹבוֹת נִסִּים וְנִפְלָאוֹת שֶׁעָשִׂיתָ עִם אֲבוֹתֵינוּ וְעִמָּנוּ מִלְּפָנִים. מִמִּצְרַיִם גְּאַלְתָּנוּ, יְהוָה אֱלֹהֵינוּ, וּמִבֵּית עֲבָדִים פְּדִיתָנוּ, בְּרָעָב זַנְתָּנוּ וּבְשָׂבָע כִּלְכַּלְתָּנוּ, מֵחֶרֶב הִצַּלְתָּנוּ וּמִדֶּבֶר מִלַּטְתָּנוּ, וּמֵחֳלָיִם רָעִים וְרַבִּים וְנֶאֱמָנִים דִּלִּיתָנוּ.
עַד הֵנָּה עֲזָרוּנוּ רַחֲמֶיךָ וְלֹא עֲזָבוּנוּ חֲסָדֶיךָ, יְהוָה אֱלֹהֵינוּ, וְאַל תִּטְּשֵׁנוּ, יְהוָה אֱלֹהֵינוּ, לָנֶצַח. עַל כֵּן אֵבָרִים שֶׁפִּלַּגְתָּ בָּנוּ וְרוּחַ וּנְשָׁמָה שֶׁנָּפַחְתָּ בְּאַפֵּינוּ וְלָשׁוֹן אֲשֶׁר שַׂמְתָּ בְּפִינוּ, הֵן הֵם יוֹדוּ וִיבָרְכוּ וִישַׁבְּחוּ וִיפָאֲרוּ וִישׁוֹרְרוּ וִירוֹמְמוּ וְיַעֲרִיצוּ וְיַקְדִּישׁוּ וְיַמְלִיכוּ אֶת שִׁמְךָ מַלְכֵּנוּ תָּמִיד.
כִּי כָל פֶּה לְךָ יוֹדֶה, וְכָל לָשׁוֹן לְךָ תִשָּׁבַע, וְכָל עַיִן לְךָ תְּצַפֶּה, וְכָל בֶּרֶךְ לְךָ תִכְרַע, וְכָל קוֹמָה לְפָנֶיךָ תִשְׁתַּחֲוֶה, וְכָל הַלְּבָבוֹת יִירָאוּךָ, וְכָל קֶרֶב וּכְלָיוֹת יְזַמְּרוּ לִשְׁמֶךָ, כַּדָּבָר שֶׁכָּתוּב: כָּל עַצְמוֹתַי תֹּאמַרְנָה, יְהוָה מִי כָמוֹךָ, מַצִּיל עָנִי מֵחָזָק מִמֶּנּוּ, וְעָנִי וְאֶבְיוֹן מִגֹּזְלוֹ.
שַׁוְעַת עֲנִיִּים אַתָּה תִשְׁמַע, צַעֲקַת הַדַּל תַּקְשִׁיב וְתוֹשִׁיעַ. מִי יִדְמֶה לָּךְ וּמִי יִשְׁוֶה לָּךְ וּמִי יַעֲרָךְ לָךְ, הָאֵל הַגָּדוֹל, הַגִּבּוֹר וְהַנּוֹרָא, אֵל עֶלְיוֹן, קֹנֵה שָׁמַיִם וָאָרֶץ. נְהַלֶּלְךָ וּנְשַׁבֵּחֲךָ וּנְפָאֶרְךָ וּנְבָרֵךְ אֶת שֵׁם קָדְשֶׁךָ, כָּאָמוּר: לְדָוִד, בָּרֲכִי נַפְשִׁי אֶת יְהוָה, וְכָל קְרָבַי אֶת שֵׁם קָדְשׁוֹ.`,

  phonetic: `Nichmat kol haï tévarekh èt chimkha, Adonaï Élohénou, vérouah kol bassar téfaèr outéromèm zikhrekha, malkénou, tamid. Min haolam véad haolam Ata Él, oumibalédékha èn lanou mélèkh goèl oumochia, podè oumatsil oumfarnèss véoné oumrahèm békhol èt tsara vétsouka. Èn lanou mélèkh ozèr vésomèkh éla Ata. Élohé harichonim véhaaharonim, Éloha kol bériyot, Adone kol toladot, hamhoulal bérov hatichbahot, hamnahèg olamo béhèssèd ouvriyotav bérahamim. VAdonaï èr hiné lo yanoum vélo yichane, hamorèr yéchénim véhamékits nirdamim, véhamessiah ilémim véhamatir assourim véhassomèkh nofélim véhazokèf kéfoufim véhamfanéah néélamim. Oulkha lévadékha anahnou modim.
Vé'ilou pinou malé chira kayam, oulchonénou rina kahamone galav, vésiftoténou chévah kémèrhavé rakia, vé'énénou méirot kachémèch vékhayaréah, véyadénou féroussot kénichré chamayim, véraglénou kalot kaayalot, èn anahnou maspikim léhodot lékha, Adonaï Élohénou vÉlohé avoténou, oulvarekh èt chimkha malkénou al ahat méélèf, élèf alfé alafim véribé révavot péamim, hatovot nissim vénifla'ot ché'assita im avoténou vé'imanou miléfanim. Mimitsrayim géaltanou, Adonaï Élohénou, oumibèt avadim péditanou, béra'av zantanou ouvsava kilkaltanou, méhèrèv hitsaltanou oumidèvèr milatatanou, ouméholayim ra'im vérabim vénééémanim dilitanou.
Ad héna azarounou rahamékha vélo azavounou hassadékha, Adonaï Élohénou, vé'al titchénou, Adonaï Élohénou, lanétsah. Al kèn évarim chépilagta banou vérouah ouchnama chénafahta béapénou vélachone achèr samta béfinou, hèn hèm yodou vivarékhou vichabéhou vifaarou vichorérou virométou véyaaritsou véyakdichou véyamlikhou èt chimkha malkénou tamid.
Ki khol pè lékha yodè, vékhol lachone lékha tichava, vékhol ayin lékha tétsapè, vékhol bérèkh lékha tikhra, vékhol koma léfanékha tichtahavè, vékhol halévavot yiraoukha, vékhol kérèv oukhlayot yézamérou lichmékha, kadavar chékatouv : Kol atsmotaï tomarna, Adonaï mi khamokha, matsil ani méhazak miménou, vé'ani vé'évyone migozlo.
Chav'at aniyim Ata tichma, tsa'akat hadal takchiv vétochia. Mi yidmè lakh oumi yichvè lakh oumi ya'arokh lakh, hAél hagadol, haguibor véhanora, Él élyone, koné chamayim vaarèts. Néhalèlekha ounchabéhakha ounfaèrkha ounvarèkh èt chèm kodchékha, kaamour : LéDavid, barékhi nafchi èt Adonaï, vékhol kéravaï èt chèm kodcho.`,

  french: `L'âme de tout être vivant bénira Ton Nom, Éternel notre Dieu, et l'esprit de toute chair glorifiera et élèvera Ton souvenir, notre Roi, en permanence. D'éternité en éternité Tu es Dieu, et en dehors de Toi nous n'avons ni Roi, ni Libérateur, ni Sauveur — qui délivre, sauve, nourrit, exauce et prend en pitié dans tout moment de détresse et d'angoisse. Nous n'avons d'autre Roi qui secoure et qui soutienne, que Toi. Dieu des premiers et des derniers, Dieu de toutes les créatures, Maître de toutes les générations, loué par d'innombrables louanges, qui dirige Son monde avec bonté et Ses créatures avec miséricorde. L'Éternel veille : Il ne sommeille ni ne dort. Il réveille ceux qui dorment, fait sortir du sommeil ceux qui sont assoupis, fait parler les muets, libère les enchaînés, soutient ceux qui tombent, redresse les courbés, dévoile les mystères. À Toi seul nous rendons grâce.
Quand bien même notre bouche serait pleine de chants comme la mer, notre langue d'allégresse comme le tumulte de ses vagues, nos lèvres de louanges comme l'étendue du firmament, nos yeux brillants comme le soleil et la lune, nos mains déployées comme les aigles du ciel, nos pieds aussi légers que les biches, nous ne pourrions Te rendre grâce suffisamment, Éternel notre Dieu et Dieu de nos pères, ni bénir Ton Nom, notre Roi, pour un seul des milliers de milliers et myriades de myriades de bontés, miracles et prodiges que Tu as accomplis envers nos pères et envers nous, autrefois. D'Égypte Tu nous as délivrés, Éternel notre Dieu, de la maison de servitude Tu nous as rachetés ; dans la famine Tu nous as nourris, dans l'abondance Tu nous as entretenus ; de l'épée Tu nous as sauvés, de la peste Tu nous as préservés, et des maladies graves, nombreuses et tenaces Tu nous as relevés.
Jusqu'ici Ta miséricorde nous a secourus, et Tes bontés ne nous ont pas abandonnés, Éternel notre Dieu ; ne nous abandonne pas, Éternel notre Dieu, à jamais. C'est pourquoi les membres que Tu as façonnés en nous, le souffle et l'âme que Tu as insufflés dans nos narines, et la langue que Tu as placée dans notre bouche — eux-mêmes Te reconnaîtront, Te béniront, Te loueront, Te glorifieront, Te chanteront, T'élèveront, Te vénéreront, Te sanctifieront et proclameront la royauté de Ton Nom, notre Roi, à jamais.
Car toute bouche Te reconnaîtra, toute langue Te jurera fidélité, tout œil se tournera vers Toi, tout genou pliera devant Toi, toute stature se prosternera devant Toi, tous les cœurs Te craindront, et toutes les entrailles chanteront pour Ton Nom, comme il est écrit : « Tous mes os diront : Éternel, qui est comme Toi ? Tu sauves l'opprimé de plus fort que lui, le pauvre et l'indigent de celui qui le dépouille. »
Tu écoutes le cri des pauvres, Tu prêtes l'oreille à la clameur du faible et Tu le délivres. Qui peut Te ressembler, Te valoir, T'égaler, Dieu grand, puissant et redoutable, Dieu Très-Haut, créateur des cieux et de la terre ? Nous Te louerons, Te glorifierons, Te magnifierons, et bénirons Ton saint Nom, comme il est dit : « De David. Bénis l'Éternel, ô mon âme, et que tout mon être bénisse Son saint Nom. »`,
};
