// Nichmat Kol Haï + Yichtabach — texte du Siddour Sefarad / Édot HaMizrah
// (suivi page par page de la photo du Siddour fournie)
export const NICHMAT_PRAYER = {
  hebrew: `נִשְׁמַת כָּל חַי תְּבָרֵךְ אֶת שִׁמְךָ יְהוָה אֱלֹהֵינוּ, וְרוּחַ כָּל בָּשָׂר תְּפָאֵר וּתְרוֹמֵם זִכְרְךָ מַלְכֵּנוּ תָּמִיד, מִן הָעוֹלָם וְעַד הָעוֹלָם אַתָּה אֵל, וּמִבַּלְעָדֶיךָ אֵין לָנוּ מֶלֶךְ גּוֹאֵל וּמוֹשִׁיעַ, פּוֹדֶה וּמַצִּיל וְעוֹנֶה וּמְרַחֵם בְּכָל עֵת צָרָה וְצוּקָה, אֵין לָנוּ מֶלֶךְ עוֹזֵר וְסוֹמֵךְ אֶלָּא אָתָּה.
אֱלֹהֵי הָרִאשׁוֹנִים וְהָאַחֲרוֹנִים, אֱלוֹהַּ כָּל בְּרִיּוֹת, אֲדוֹן כָּל תּוֹלָדוֹת, הַמְהֻלָּל בְּכָל הַתִּשְׁבָּחוֹת, הַמְנַהֵג עוֹלָמוֹ בְּחֶסֶד וּבְרִיּוֹתָיו בְּרַחֲמִים. וַיהוָה עֵר, לֹא יָנוּם וְלֹא יִישָׁן, הַמְעוֹרֵר יְשֵׁנִים וְהַמֵּקִיץ נִרְדָּמִים, מְחַיֵּה מֵתִים וְרוֹפֵא חוֹלִים, פּוֹקֵחַ עִוְרִים וְזוֹקֵף כְּפוּפִים, הַמֵּשִׂיחַ אִלְּמִים וְהַמְפַעֲנֵחַ נֶעֱלָמִים, וּלְךָ לְבַדְּךָ אֲנַחְנוּ מוֹדִים.
וְאִלּוּ פִינוּ מָלֵא שִׁירָה כַּיָּם, וּלְשׁוֹנֵנוּ רִנָּה כַּהֲמוֹן גַּלָּיו, וְשִׂפְתוֹתֵינוּ שֶׁבַח כְּמֶרְחֲבֵי רָקִיעַ, וְעֵינֵינוּ מְאִירוֹת כַּשֶּׁמֶשׁ וְכַיָּרֵחַ, וְיָדֵינוּ פְרוּשׂוֹת כְּנִשְׂרֵי שָׁמַיִם, וְרַגְלֵינוּ קַלּוֹת כָּאַיָּלוֹת, אֵין אָנוּ מַסְפִּיקִים לְהוֹדוֹת לְךָ יְהוָה אֱלֹהֵינוּ, וּלְבָרֵךְ אֶת שִׁמְךָ מַלְכֵּנוּ, עַל אַחַת מֵאֶלֶף אַלְפֵי אֲלָפִים וְרֹב רִבֵּי רְבָבוֹת פְּעָמִים, הַטּוֹבוֹת, נִסִּים וְנִפְלָאוֹת שֶׁעָשִׂיתָ עִמָּנוּ וְעִם אֲבוֹתֵינוּ מִלְּפָנִים. מִמִּצְרַיִם גְּאַלְתָּנוּ יְהוָה אֱלֹהֵינוּ, מִבֵּית עֲבָדִים פְּדִיתָנוּ, בְּרָעָב זַנְתָּנוּ וּבְשָׂבָע כִּלְכַּלְתָּנוּ, מֵחֶרֶב הִצַּלְתָּנוּ וּמִדֶּבֶר מִלַּטְתָּנוּ, וּמֵחֳלָאִים רָעִים וְרַבִּים דִּלִּיתָנוּ.
עַד הֵנָּה עֲזָרוּנוּ רַחֲמֶיךָ, וְלֹא עֲזָבוּנוּ חֲסָדֶיךָ. עַל כֵּן אֵבָרִים שֶׁפִּלַּגְתָּ בָּנוּ, וְרוּחַ וּנְשָׁמָה שֶׁנָּפַחְתָּ בְּאַפֵּינוּ, וְלָשׁוֹן אֲשֶׁר שַׂמְתָּ בְּפִינוּ, הֵן הֵם יוֹדוּ וִיבָרְכוּ וִישַׁבְּחוּ וִיפָאֲרוּ וִישׁוֹרְרוּ אֶת שִׁמְךָ מַלְכֵּנוּ תָּמִיד. כִּי כָל פֶּה לְךָ יוֹדֶה, וְכָל לָשׁוֹן לְךָ תְשַׁבַּח, וְכָל עַיִן לְךָ תְצַפֶּה, וְכָל בֶּרֶךְ לְךָ תִכְרַע, וְכָל קוֹמָה לְפָנֶיךָ תִשְׁתַּחֲוֶה, וְהַלְּבָבוֹת יִירָאוּךָ, וְכָל קֶרֶב וּכְלָיוֹת יְזַמְּרוּ לִשְׁמֶךָ, כַּדָּבָר שֶׁנֶּאֱמַר: כָּל עַצְמוֹתַי תֹּאמַרְנָה יְהוָה מִי כָמוֹךָ, מַצִּיל עָנִי מֵחָזָק מִמֶּנּוּ, וְעָנִי וְאֶבְיוֹן מִגֹּזְלוֹ.
שַׁוְעַת עֲנִיִּים אַתָּה תִשְׁמַע, צַעֲקַת הַדַּל תַּקְשִׁיב וְתוֹשִׁיעַ. וְכָתוּב: רַנְּנוּ צַדִּיקִים בַּיהוָה, לַיְשָׁרִים נָאוָה תְהִלָּה.
בְּפִי יְשָׁרִים תִּתְרוֹמָם, וּבְשִׂפְתֵי צַדִּיקִים תִּתְבָּרַךְ, וּבִלְשׁוֹן חֲסִידִים תִּתְקַדָּשׁ, וּבְקֶרֶב קְדוֹשִׁים תִּתְהַלָּל.
בְּמִקְהֲלוֹת רִבְבוֹת עַמְּךָ בֵּית יִשְׂרָאֵל, שֶׁכֵּן חוֹבַת כָּל הַיְצוּרִים לְפָנֶיךָ יְהוָה אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ, לְהוֹדוֹת, לְהַלֵּל, לְשַׁבֵּחַ, לְפָאֵר, לְרוֹמֵם, לְהַדֵּר וּלְנַצֵּחַ, עַל כָּל דִּבְרֵי שִׁירוֹת וְתִשְׁבָּחוֹת דָּוִד בֶּן יִשַׁי עַבְדְּךָ מְשִׁיחֶךָ. וּבְכֵן
יִשְׁתַּבַּח שִׁמְךָ לָעַד מַלְכֵּנוּ, הָאֵל הַמֶּלֶךְ הַגָּדוֹל וְהַקָּדוֹשׁ בַּשָּׁמַיִם וּבָאָרֶץ, כִּי לְךָ נָאֶה יְהוָה אֱלֹהֵינוּ וֵאלֹהֵי אֲבוֹתֵינוּ לְעוֹלָם וָעֶד: שִׁיר וּשְׁבָחָה, הַלֵּל וְזִמְרָה, עֹז וּמֶמְשָׁלָה, נֶצַח, גְּדֻלָּה וּגְבוּרָה, תְּהִלָּה וְתִפְאֶרֶת, קְדֻשָּׁה וּמַלְכוּת, בְּרָכוֹת וְהוֹדָאוֹת, לְשִׁמְךָ הַגָּדוֹל וְהַקָּדוֹשׁ, וּמֵעוֹלָם וְעַד עוֹלָם אַתָּה אֵל. בָּרוּךְ אַתָּה יְהוָה, מֶלֶךְ גָּדוֹל וּמְהֻלָּל בַּתִּשְׁבָּחוֹת, אֵל הַהוֹדָאוֹת, אֲדוֹן הַנִּפְלָאוֹת, בּוֹרֵא כָּל הַנְּשָׁמוֹת, רִבּוֹן כָּל הַמַּעֲשִׂים, הַבּוֹחֵר בְּשִׁירֵי זִמְרָה, מֶלֶךְ אֵל חַי הָעוֹלָמִים. אָמֵן.`,

  phonetic: `Nichmat kol haï tévarekh èt chimkha Adonaï Élohénou, vérouah kol bassar téfaèr outéromèm zikhrekha malkénou tamid, min haolam véad haolam Ata Él, oumibalédékha èn lanou mélèkh goèl oumochia, podè oumatsil véoné oumrahèm békhol èt tsara vétsouka, èn lanou mélèkh ozèr vésomèkh éla Ata.
Élohé harichonim véhaaharonim, Éloha kol bériyot, Adone kol toladot, hamhoulal békhol hatichbahot, hamnahèg olamo béhèssèd ouvriyotav bérahamim. VAdonaï èr, lo yanoum vélo yichane, hamorèr yéchénim véhamékits nirdamim, méhayé métim vérofé holim, pokéah ivrim vézokèf kéfoufim, hamessiah ilémim véhamfanéah néélamim, oulkha lévadékha anahnou modim.
Vé'ilou pinou malé chira kayam, oulchonénou rina kahamone galav, vésiftoténou chévah kémèrhavé rakia, vé'énénou méirot kachémèch vékhayaréah, véyadénou féroussot kénichré chamayim, véraglénou kalot kaayalot, èn anou maspikim léhodot lékha Adonaï Élohénou, oulvarekh èt chimkha malkénou, al ahat méélèf alfé alafim vérov ribé révavot péamim, hatovot, nissim vénifla'ot ché'assita imanou vé'im avoténou miléfanim. Mimitsrayim géaltanou Adonaï Élohénou, mibèt avadim péditanou, béra'av zantanou ouvsava kilkaltanou, méhèrèv hitsaltanou oumidèvèr milatatanou, ouméholaïm ra'im vérabim dilitanou.
Ad héna azarounou rahamékha, vélo azavounou hassadékha. Al kèn évarim chépilagta banou, vérouah ouchnama chénafahta béapénou, vélachone achèr samta béfinou, hèn hèm yodou vivarékhou vichabéhou vifaarou vichorérou èt chimkha malkénou tamid. Ki khol pè lékha yodè, vékhol lachone lékha téchabah, vékhol ayin lékha tétsapè, vékhol bérèkh lékha tikhra, vékhol koma léfanékha tichtahavè, véhalévavot yiraoukha, vékhol kérèv oukhlayot yézamérou lichmékha, kadavar chénééémar : Kol atsmotaï tomarna Adonaï mi khamokha, matsil ani méhazak miménou, vé'ani vé'évyone migozlo.
Chav'at aniyim Ata tichma, tsa'akat hadal takchiv vétochia. Vékhatouv : Ranénou tsadikim bAdonaï, layécharim nava téhila.
Béfi yécharim titromam, ouvsifté tsadikim titbarakh, ouvilchone hassidim titkadach, ouvkérèv kédochim tit'halal.
Bémikhalot rivévot amékha bèt Yisraèl, chékèn hovat kol haytsourim léfanékha Adonaï Élohénou vÉlohé avoténou, léhodot, léhalèl, léchabéah, léfaèr, léromèm, léhadèr oulnatséah, al kol divré chirot vétichbahot David bèn Yichaï avdékha méchihékha. Ouvkhèn
Yichtabah chimkha la'ad malkénou, hAél hamélèkh hagadol véhakadoch bachamayim ouvaarèts, ki lékha naè Adonaï Élohénou vÉlohé avoténou lé'olam va'èd : Chir ouchvaha, halèl vézimra, oz oumèmchala, nétsah, guédoula ouguévoura, téhila vétifèrèt, kéducha oumalkhout, brakhot véhoda'ot, léchimkha hagadol véhakadoch, ouméolam véad olam Ata Él. Baroukh Ata Adonaï, mélèkh gadol oumhoulal batichbahot, Él hahoda'ot, Adone hanifla'ot, boré kol hanéchamot, ribone kol hama'assim, habohèr béchiré zimra, mélèkh Él haï haolamim. Amèn.`,

  french: `L'âme de tout être vivant bénira Ton Nom, Éternel notre Dieu, et l'esprit de toute chair glorifiera et élèvera Ton souvenir, notre Roi, à jamais. D'éternité en éternité Tu es Dieu, et en dehors de Toi nous n'avons ni Roi, ni Libérateur, ni Sauveur — qui délivre, sauve, exauce et prend en pitié dans tout temps de détresse et d'angoisse. Nous n'avons d'autre Roi qui secourt et soutient, que Toi.
Dieu des premiers et des derniers, Dieu de toutes les créatures, Maître de toutes les générations, célébré par toutes les louanges, qui dirige Son monde avec bonté et Ses créatures avec miséricorde. L'Éternel veille, Il ne sommeille ni ne dort. Il réveille ceux qui dorment, fait sortir du sommeil ceux qui sont assoupis, ressuscite les morts et guérit les malades, ouvre les yeux des aveugles et redresse ceux qui sont courbés, fait parler les muets et dévoile les choses cachées. À Toi seul nous rendons grâce.
Quand notre bouche serait pleine de chants comme la mer, notre langue d'allégresse comme le tumulte de ses vagues, nos lèvres de louanges comme l'étendue du firmament, nos yeux brillants comme le soleil et la lune, nos mains déployées comme les aigles du ciel, nos pieds aussi légers que les biches, nous ne pourrions Te rendre grâce suffisamment, Éternel notre Dieu, ni bénir Ton Nom, notre Roi, pour une seule sur les milliers de milliers et myriades de myriades de bontés, miracles et prodiges que Tu as accomplis envers nous et envers nos pères, autrefois. D'Égypte Tu nous as délivrés, Éternel notre Dieu, de la maison de servitude Tu nous as rachetés ; dans la famine Tu nous as nourris, dans l'abondance Tu nous as entretenus ; de l'épée Tu nous as sauvés, de la peste Tu nous as préservés, et des maladies graves et nombreuses Tu nous as relevés.
Jusqu'ici Ta miséricorde nous a secourus, et Tes bontés ne nous ont pas abandonnés. C'est pourquoi les membres que Tu as façonnés en nous, le souffle et l'âme que Tu as insufflés dans nos narines, et la langue que Tu as placée dans notre bouche — eux-mêmes Te reconnaîtront, Te béniront, Te loueront, Te glorifieront et Te chanteront, ô notre Roi, à jamais. Car toute bouche Te reconnaîtra, toute langue Te louera, tout œil se tournera vers Toi, tout genou pliera devant Toi, toute stature se prosternera devant Toi, et les cœurs Te craindront, et toutes les entrailles chanteront pour Ton Nom, comme il est dit : « Tous mes os diront : Éternel, qui est comme Toi ? Tu sauves l'opprimé de plus fort que lui, le pauvre et l'indigent de celui qui le dépouille. »
Tu écoutes le cri des pauvres, Tu prêtes l'oreille à la clameur du faible et Tu le délivres. Et il est écrit : « Justes, chantez l'Éternel, aux hommes droits sied la louange. »
Par la bouche des hommes droits Tu seras exalté, par les lèvres des justes Tu seras béni, par la langue des pieux Tu seras sanctifié, et au sein des saints Tu seras loué.
Dans les assemblées des myriades de Ton peuple, la maison d'Israël, car tel est le devoir de toutes les créatures devant Toi, Éternel notre Dieu et Dieu de nos pères : reconnaître, louer, célébrer, glorifier, exalter, magnifier et triompher, par toutes les paroles de cantiques et de louanges de David fils de Jessé, Ton serviteur, Ton oint. Et ainsi :
Que Ton Nom soit loué à jamais, notre Roi, Dieu, Roi grand et saint dans les cieux et sur la terre, car à Toi conviennent, Éternel notre Dieu et Dieu de nos pères, à tout jamais : cantique et louange, hymne et chant, force et empire, victoire, grandeur et puissance, gloire et splendeur, sainteté et royauté, bénédictions et actions de grâces, à Ton Nom grand et saint, et d'éternité en éternité Tu es Dieu. Béni sois-Tu, Éternel, Roi grand, célébré par les louanges, Dieu des reconnaissances, Maître des merveilles, Créateur de toutes les âmes, Souverain de toutes les œuvres, qui agrée les chants de cantique, Roi, Dieu vivant des mondes. Amen.`,
};
