project_id = "kkocryqhlieoyhtsqlns"

[functions.send-push]
verify_jwt = false

[functions.shabbat-reminder]
verify_jwt = false

[functions.create-donation-checkout]
verify_jwt = false

[functions.stripe-donation-webhook]
verify_jwt = false

[functions.stripe-connect-onboard]
verify_jwt = false

[functions.check-stripe-onboard]
verify_jwt = false

[functions.generate-cerfa]
verify_jwt = false

[functions.send-cerfa-email]
verify_jwt = false

[functions.omer-reminder]
verify_jwt = false

[functions.get-donation-cerfa]
verify_jwt = false

[functions.places-autocomplete]
verify_jwt = false
