import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Heart, ExternalLink, Loader2, Check, CreditCard, Download, Copy, Link2, BarChart3, Settings, List, Megaphone, FileCheck, BellRing, Share2 } from "lucide-react";
// jsPDF removed: CERFA is now generated by the edge function in official 2041-RD format.
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import CampaignsManager from "./CampaignsManager";
import DonsStats from "./DonsStats";
import CerfaConfig from "./CerfaConfig";
import DonationReminders from "./DonationReminders";
import { shareCerfaPdf } from "@/lib/cerfaPdf";
...
  const shareCerfa = async (donation: Donation) => {
    if (!cerfaConfigured) {
      toast.error("Configurez d'abord les informations légales (onglet CERFA).");
      return;
    }
    if (!donation.cerfa_token) {
      toast.error("Reçu indisponible (token manquant).");
      return;
    }

    await shareCerfaPdf(donation.cerfa_token);
  };

  const exportCsv = () => {
    if (!donations.length) return;
    const header = "Date,Donateur,Email,Montant (€),CERFA\n";
    const rows = donations.map((d) =>
      `${new Date(d.created_at).toLocaleDateString("fr-FR")},"${d.donor_name}","${d.donor_email}",${(d.amount / 100).toFixed(2)},${d.cerfa_generated ? "Oui" : "Non"}`
    ).join("\n");
    const blob = new Blob([header + rows], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dons-${synagogueName || "export"}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (loading) return <div className="text-center py-8 text-muted-foreground text-sm">Chargement…</div>;
  if (!profileId) return <div className="text-center py-8 text-muted-foreground text-sm">Créez d'abord votre profil synagogue.</div>;

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3 mb-2">
        <Heart className="w-5 h-5 text-primary" />
        <h3 className="font-display text-base font-bold text-foreground">Module Dons</h3>
      </div>

      <Tabs defaultValue="stats" className="w-full">
        <TabsList className="w-full grid grid-cols-6 h-auto p-1">
          <TabsTrigger value="stats" className="text-[10px] py-1.5 gap-0.5 flex-col">
            <BarChart3 className="w-3.5 h-3.5" /> Stats
          </TabsTrigger>
          <TabsTrigger value="campagnes" className="text-[10px] py-1.5 gap-0.5 flex-col">
            <Megaphone className="w-3.5 h-3.5" /> Camp.
          </TabsTrigger>
          <TabsTrigger value="historique" className="text-[10px] py-1.5 gap-0.5 flex-col">
            <List className="w-3.5 h-3.5" /> Dons
          </TabsTrigger>
          <TabsTrigger value="relances" className="text-[10px] py-1.5 gap-0.5 flex-col">
            <BellRing className="w-3.5 h-3.5" /> Relan.
          </TabsTrigger>
          <TabsTrigger value="cerfa" className="text-[10px] py-1.5 gap-0.5 flex-col">
            <FileCheck className="w-3.5 h-3.5" /> CERFA
          </TabsTrigger>
          <TabsTrigger value="config" className="text-[10px] py-1.5 gap-0.5 flex-col">
            <Settings className="w-3.5 h-3.5" /> Stripe
          </TabsTrigger>
        </TabsList>

        {/* Stats tab */}
        <TabsContent value="stats" className="mt-4">
          {!stripeOnboarded ? (
            <div className="rounded-xl border border-dashed border-border bg-card p-6 text-center">
              <p className="text-sm text-muted-foreground">Configurez Stripe (onglet Config) pour activer les statistiques.</p>
            </div>
          ) : (
            <DonsStats synagogueId={profileId} />
          )}
        </TabsContent>

        {/* Campagnes tab */}
        <TabsContent value="campagnes" className="mt-4">
          {!stripeOnboarded ? (
            <div className="rounded-xl border border-dashed border-border bg-card p-6 text-center">
              <p className="text-sm text-muted-foreground">Configurez Stripe (onglet Config) avant de créer des campagnes.</p>
            </div>
          ) : (
            <CampaignsManager synagogueId={profileId} />
          )}
        </TabsContent>

        {/* Historique tab */}
        <TabsContent value="historique" className="mt-4">
          <div className="rounded-xl border border-border bg-card p-4 space-y-3">
            <div className="flex items-center justify-between">
              <Label className="text-xs font-semibold">Historique des dons</Label>
              {donations.length > 0 && (
                <Button variant="ghost" size="sm" onClick={exportCsv} className="text-xs h-7">
                  <Download className="w-3 h-3 mr-1" /> CSV
                </Button>
              )}
            </div>

            {loadingDonations ? (
              <div className="text-center py-4"><Loader2 className="w-4 h-4 animate-spin mx-auto" /></div>
            ) : donations.length === 0 ? (
              <p className="text-xs text-muted-foreground text-center py-4">Aucun don reçu pour le moment.</p>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-border text-left text-muted-foreground">
                      <th className="pb-2 pr-2">Date</th>
                      <th className="pb-2 pr-2">Donateur</th>
                      <th className="pb-2 pr-2">Montant</th>
                      <th className="pb-2">CERFA</th>
                    </tr>
                  </thead>
                  <tbody>
                    {donations.map((d) => (
                      <tr key={d.id} className="border-b border-border/50">
                        <td className="py-2 pr-2">{new Date(d.created_at).toLocaleDateString("fr-FR")}</td>
                        <td className="py-2 pr-2 max-w-[100px] truncate">{d.donor_name || d.donor_email}</td>
                        <td className="py-2 pr-2 font-semibold">{(d.amount / 100).toFixed(2)} €</td>
                        <td className="py-2">
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => openOfficialCerfa(d)}
                              disabled={!cerfaConfigured}
                              className="text-primary hover:underline cursor-pointer bg-transparent border-none text-xs disabled:opacity-50 disabled:cursor-not-allowed disabled:no-underline inline-flex items-center gap-1"
                              title={cerfaConfigured ? "Télécharger / ouvrir le reçu CERFA" : "Configurez d'abord l'onglet CERFA"}
                            >
                              <Download className="w-3 h-3" /> CERFA
                            </button>
                            <button
                              onClick={() => shareCerfa(d)}
                              disabled={!cerfaConfigured || !d.cerfa_token}
                              className="text-primary hover:underline cursor-pointer bg-transparent border-none text-xs disabled:opacity-50 disabled:cursor-not-allowed disabled:no-underline inline-flex items-center gap-1"
                              title="Partager le lien du reçu CERFA"
                            >
                              <Share2 className="w-3 h-3" /> Partager
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </TabsContent>

        {/* Relances tab */}
        <TabsContent value="relances" className="mt-4">
          {!stripeOnboarded ? (
            <div className="rounded-xl border border-dashed border-border bg-card p-6 text-center">
              <p className="text-sm text-muted-foreground">Configurez Stripe (onglet Stripe) avant d'envoyer des relances.</p>
            </div>
          ) : (
            <DonationReminders synagogueId={profileId} synagogueName={synagogueName} />
          )}
        </TabsContent>

        {/* CERFA tab */}
        <TabsContent value="cerfa" className="mt-4">
          <CerfaConfig synagogueId={profileId} />
        </TabsContent>

        {/* Config tab */}
        <TabsContent value="config" className="mt-4 space-y-4">
          {/* Stripe Connect Setup */}
          <div className="rounded-xl border border-border bg-card p-4 space-y-3">
            <div className="flex items-center gap-2">
              <CreditCard className="w-4 h-4 text-primary" />
              <Label className="text-xs font-semibold">Configuration Stripe Connect</Label>
            </div>

            {stripeOnboarded ? (
              <div className="flex items-center gap-2 text-green-600 bg-green-50 rounded-lg p-3">
                <Check className="w-4 h-4" />
                <span className="text-xs font-semibold">Paiements activés ✓</span>
              </div>
            ) : stripeExists ? (
              <div className="space-y-2">
                <p className="text-xs text-amber-600 bg-amber-50 rounded-lg p-3">
                  ⏳ L'onboarding Stripe n'est pas terminé. Cliquez ci-dessous pour le compléter.
                </p>
                <Button onClick={handleStripeOnboard} disabled={onboarding} variant="outline" className="w-full">
                  {onboarding ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <CreditCard className="w-4 h-4 mr-2" />}
                  Compléter la configuration Stripe
                </Button>
              </div>
            ) : (
              <div className="space-y-2">
                <p className="text-[11px] text-muted-foreground">
                  Connectez votre compte bancaire via Stripe pour recevoir les dons directement.
                  Une commission de 4% est prélevée automatiquement.
                </p>
                <Button onClick={handleStripeOnboard} disabled={onboarding} className="w-full">
                  {onboarding ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <CreditCard className="w-4 h-4 mr-2" />}
                  Configurer mes paiements (Stripe)
                </Button>
              </div>
            )}
          </div>

          {/* Donation Link - Create */}
          {stripeOnboarded && !donationSlug && (
            <div className="rounded-xl border border-border bg-card p-4 space-y-3">
              <div className="flex items-center gap-2">
                <Link2 className="w-4 h-4 text-primary" />
                <Label className="text-xs font-semibold">Créer votre lien de don</Label>
              </div>
              <p className="text-[11px] text-muted-foreground">
                Choisissez un identifiant court pour votre page de don (ex: beth-yaakov, synagogue-paris).
              </p>
              <div className="flex items-center gap-2">
                <Input
                  value={newSlug}
                  onChange={(e) => setNewSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-").replace(/-+/g, "-"))}
                  placeholder="mon-synagogue"
                  className="text-xs"
                />
                <Button
                  size="sm"
                  onClick={async () => {
                    if (!newSlug.trim() || newSlug.length < 3) {
                      toast.error("Le slug doit faire au moins 3 caractères");
                      return;
                    }
                    setSavingSlug(true);
                    const { error } = await (supabase
                      .from("synagogue_stripe_accounts" as any)
                      .update({ custom_donation_slug: newSlug.trim() }) as any)
                      .eq("synagogue_id", profileId);
                    setSavingSlug(false);
                    if (error) {
                      toast.error("Erreur : ce slug est peut-être déjà pris");
                    } else {
                      setDonationSlug(newSlug.trim());
                      toast.success("Lien de don créé !");
                    }
                  }}
                  disabled={savingSlug || !newSlug.trim()}
                >
                  {savingSlug ? <Loader2 className="w-4 h-4 animate-spin" /> : "Créer"}
                </Button>
              </div>
            </div>
          )}

          {/* Donation Link - Display */}
          {donationSlug && (
            <div className="rounded-xl border border-border bg-card p-4 space-y-3">
              <div className="flex items-center gap-2">
                <Link2 className="w-4 h-4 text-primary" />
                <Label className="text-xs font-semibold">Lien de don unique</Label>
              </div>
              <div className="flex items-center gap-2">
                <Input value={donationUrl} readOnly className="text-xs" />
                <Button size="icon" variant="outline" onClick={copyUrl}>
                  <Copy className="w-4 h-4" />
                </Button>
              </div>
              <div className="flex items-center gap-2 flex-wrap">
                <a href={donationUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-xs text-primary hover:underline">
                  <ExternalLink className="w-3 h-3" /> Voir la page
                </a>
                <button
                  onClick={() => {
                    const text = `🕍 ${synagogueName} — Faire un don\n\n💛 Soutenez notre communauté en faisant un don sécurisé :\n${donationUrl}\n\nMerci pour votre générosité !`;
                    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank");
                  }}
                  className="inline-flex items-center gap-1 text-xs font-semibold text-green-600 hover:underline bg-transparent border-none cursor-pointer"
                >
                  📱 Partager sur WhatsApp
                </button>
              </div>
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default DonsManager;
